### Convert POSCAR to LAMMPS

Running scripts in this short tutorial depends on the following prerequisites:

- [Python](https://www.python.org/download/other/) 3.6 or newer
- [Numpy](https://numpy.org/) (Numerical Package with Python)
- [ASE](https://wiki.fysik.dtu.dk/ase/) (Atomic Simulation Environment)
- [Atomsk](https://atomsk.univ-lille.fr/) (Dealing with Atomic Data Files) 
- [Vesta](https://jp-minerals.org/vesta/en/) (Visualization for Electronic and Structural Analysis)
- [Ovito](https://www.ovito.org/) (Open Visualization Tool for Solids and Molucules)

To install these dependences, please follow the corresponding instructions in their homepages (there are also a bunch of online resources that are availabe for their installations). 

For simplicity let's take a metallic surface, e.g. Al(111), as an example to illustrate how to convert a POSCAR file to a LAMMPS file.

**STEP 1: Create a Al(111) surface using ASE and write the strucutre to a POSCAR file**

In [7]:
import numpy as np
from ase.build import fcc111, fcc110

# Create a fcc Al(111) surface with size 10x10x5
slab = fcc111('Al', size=(10,10,5))

# Center the cell along z axis and add a vacuum of 20 A
slab.center(vacuum=10, axis=2)

# Get cell parameters
cellparas = slab.get_cell()[:]
print("Cell Parameters:")
print(cellparas)

# Get atom positions
positions = slab.get_positions()
print("Atom Positions:")
print(positions)

# Write to file in POSCAR format (vasp5)
slab.write("POSCAR", format='vasp', vasp5=True, direct=False, sort=True)

Cell Parameters:
[[28.63782464  0.          0.        ]
 [14.31891232 24.80108365  0.        ]
 [ 0.          0.         29.35307436]]
Atom Positions:
[[ 0.          1.65340558 10.        ]
 [ 2.86378246  1.65340558 10.        ]
 [ 5.72756493  1.65340558 10.        ]
 ...
 [32.93349833 22.32097528 19.35307436]
 [35.7972808  22.32097528 19.35307436]
 [38.66106326 22.32097528 19.35307436]]


**STEP 2: Convert the POSCAR file to a LAMMPS file using Atomsk**

In [8]:
import os
os.system("atomsk POSCAR lammps") # Generate a LAMMPS file named POSCAR.lmp

0

Now we can use [Vesta](https://jp-minerals.org/vesta/en/) and [Ovito](https://www.ovito.org/) to visualize POSCAR and POSCAR.lmp, i.e., `vesta POSCAR` and
`ovito POSCAR.lmp`.